---
- name: Check if Oh My Zsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_installed

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_installed.stat.exists
