---
- name: Check if omz is installed
  command: omz version
  register: omz_installed
  ignore_errors: yes

- name: Install omz
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: omz_installed is failed
