---
- name: Set up development environment
  hosts: localhost
  become: no
  roles:
    - homebrew
    - git
    - zsh
    - zsh-autosuggestions
    - zsh-history-substring-search
    - zsh-syntax-highlighting
    - ohmyzsh
    - iterm2
    - vscode
    - dotfiles
    - ssh
    - tmux
    - neovim
    - ripgrep
    - autojump
    - nvm
    - lazygit
